FROM python:3.10.0-alpine

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./cmsis2 /app

WORKDIR /app

COPY entrypoint-prod.sh /
ENTRYPOINT ["sh", "/entrypoint-prod.sh"]