version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
volumes:
  static:
