# Generated by Django 4.2.4 on 2023-08-23 01:33

"""
Este es un ejemplo de docstring.

Aquí puedes proporcionar una descripción detallada de lo que hace
este archivo, clase o función.
"""

# El resto de tu código aquí


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
