# Generated by Django 4.2.4 on 2023-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='is_system_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrole',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customrole',
            name='is_system_role',
            field=models.BooleanField(default=False),
        ),
    ]
