# Generated by Django 4.2.4 on 2023-09-02 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategoryrole',
            unique_together={('user', 'category', 'role')},
        ),
    ]
