# Generated by Django 4.2.4 on 2023-11-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenidos', '0002_initial'),
        ('interacciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('leido', models.BooleanField(blank=True, default=False, null=True)),
                ('accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interacciones.accion')),
                ('contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenidos.contenido')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emisor', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
