# Generated by Django 4.2.4 on 2023-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('MAX_CANT_DENUNCIAS', 'MAX_CANT_DENUNCIAS'), ('TITULO', 'TITULO')], max_length=20, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
    ]
