# Generated by Django 4.2.4 on 2023-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='clave',
            field=models.CharField(choices=[('MAX_CANT_DENUNCIAS', 'MAX_CANT_DENUNCIAS')], max_length=20, unique=True),
        ),
    ]
