# Generated by Django 4.2.4 on 2023-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
