# Generated by Django 4.2.4 on 2023-09-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categorias.subcategoria'),
        ),
    ]
