# Generated by Django 4.2.4 on 2023-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
