# Generated by Django 4.2.4 on 2023-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='cantidad_compartir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='cantidad_me_gusta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
