# Generated by Django 4.2.4 on 2023-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_contenido_cantidad_compartir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='cantidad_comentarios',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
