# Generated by Django 4.2.4 on 2023-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_contenido_cantidad_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cantidad_denuncias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
