# Generated by Django 4.2.4 on 2023-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_alter_contenido_cantidad_denuncias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='cantidad_visualizaciones',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
